[package]
name = "wfc_too"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
crossterm = "0.28.1"
eframe = "0.30.0"
egui = "0.30.0"
rand = "0.9.0"

[lib]
name = "wfc_too"
path = "src/lib.rs"

[[bin]]
name = "generate"
path = "bin/generate.rs"
